// Domain Ontology ของ Chapter 2: สั่งอาหารและเครื่องดื่มเฉพาะทาง (Specialty Food & Drinks)
// 4 สถานการณ์ — เบเกอรี / อาหารนานาชาติ / น้ำผลไม้และมัทฉะ / ค็อกเทลและม็อกเทล (มีการตรวจบัตรยืนยันอายุ)
// ทุกค่ารองรับ 2 ภาษา (th / en), kw = คำที่ตัวแยกความหมาย Offline ใช้, q = คำที่บ่งบอกว่ากำลัง "ถาม" เรื่องนั้น (ใช้ในโหมดสลับบทบาท)

// ---------------------------------------------------------------- สารก่อภูมิแพ้
export const ALLERGENS = {
  peanut:   { th: 'ถั่วลิสง',      en: 'peanuts',   icon: '🥜', kw: ['ถั่วลิสง', 'peanut'] },
  tree_nut: { th: 'ถั่วเปลือกแข็ง', en: 'tree nuts', icon: '🌰', kw: ['ถั่วเปลือกแข็ง', 'ถั่ว', 'tree nut', 'nut'] },
  seafood:  { th: 'อาหารทะเล',     en: 'seafood',   icon: '🦐', kw: ['อาหารทะเล', 'ซีฟู้ด', 'seafood', 'shellfish', 'fish'] },
  dairy:    { th: 'นมวัว',         en: 'dairy',     icon: '🥛', kw: ['นมวัว', 'นม', 'แลคโตส', 'dairy', 'milk', 'lactose'] },
  egg:      { th: 'ไข่',           en: 'eggs',      icon: '🥚', kw: ['ไข่', 'egg'] },
  gluten:   { th: 'กลูเตน',        en: 'gluten',    icon: '🌾', kw: ['กลูเตน', 'แป้งสาลี', 'gluten', 'wheat'] },
};

// ---------------------------------------------------------------- วัตถุดิบ
export const INGREDIENTS = {
  butter:        { th: 'เนย',              en: 'butter',          allergen: 'dairy',    kw: ['เนยสด', 'เนย', 'butter'] },
  wheat_flour:   { th: 'แป้งสาลี',         en: 'wheat flour',     allergen: 'gluten',   kw: ['แป้งสาลี', 'wheat flour', 'flour'] },
  egg:           { th: 'ไข่',              en: 'egg',             allergen: 'egg',      kw: ['ไข่', 'egg'] },
  almond:        { th: 'อัลมอนด์',         en: 'almond',          allergen: 'tree_nut', kw: ['อัลมอนด์', 'almond'] },
  walnut:        { th: 'วอลนัท',           en: 'walnut',          allergen: 'tree_nut', kw: ['วอลนัท', 'walnut'] },
  cream_cheese:  { th: 'ครีมชีส',          en: 'cream cheese',    allergen: 'dairy',    kw: ['ครีมชีส', 'cream cheese'] },
  icing:         { th: 'ไอซิ่งครีมชีส',     en: 'cream-cheese icing', allergen: 'dairy', kw: ['ไอซิ่ง', 'ฟรอสติ้ง', 'icing', 'frosting'] },
  cheese:        { th: 'ชีส',              en: 'cheese',          allergen: 'dairy',    kw: ['ชีส', 'cheese'] },
  cream:         { th: 'ครีม',             en: 'cream',           allergen: 'dairy',    kw: ['ครีม', 'cream'] },
  mayo:          { th: 'มายองเนส',         en: 'mayonnaise',      allergen: 'egg',      kw: ['มายองเนส', 'มายอง', 'mayonnaise', 'mayo'] },
  bun:           { th: 'ขนมปังเบอร์เกอร์',  en: 'burger bun',      allergen: 'gluten',   kw: ['ขนมปังเบอร์เกอร์', 'bun'] },
  wheat_noodle:  { th: 'เส้นแป้งสาลี',      en: 'wheat noodles',   allergen: 'gluten',   kw: [] },
  gochujang:     { th: 'ซอสโคชูจัง',        en: 'gochujang',       allergen: 'gluten',   kw: ['โคชูจัง', 'โกชูจัง', 'ซอสพริกเกาหลี', 'gochujang'] },
  pickles:       { th: 'แตงกวาดอง',        en: 'pickles',         kw: ['แตงกวาดอง', 'ผักดอง', 'pickle'] },
  tomato:        { th: 'มะเขือเทศ',        en: 'tomato',          kw: ['มะเขือเทศ', 'tomato'] },
  onion:         { th: 'หอมใหญ่',          en: 'onion',           kw: ['หอมใหญ่', 'หัวหอม', 'onion'] },
  spring_onion:  { th: 'ต้นหอม',           en: 'spring onion',    kw: ['ต้นหอม', 'spring onion', 'green onion', 'scallion'] },
  bean_sprout:   { th: 'ถั่วงอก',          en: 'bean sprouts',    kw: ['ถั่วงอก', 'bean sprout'] },
  bamboo_shoot:  { th: 'หน่อไม้',          en: 'bamboo shoots',   kw: ['หน่อไม้', 'menma', 'bamboo shoot'] },
  coriander:     { th: 'ผักชี',            en: 'coriander',       kw: ['ผักชี', 'coriander', 'cilantro'] },
  basil:         { th: 'ใบเบซิล',          en: 'basil',           kw: ['ใบเบซิล', 'เบซิล', 'โหระพา', 'basil'] },
  bacon:         { th: 'เบคอน',            en: 'bacon',           kw: ['เบคอน', 'bacon'] },
  ginger:        { th: 'ขิง',              en: 'ginger',          kw: ['ขิง', 'ginger'] },
  celery:        { th: 'ขึ้นฉ่าย',          en: 'celery',          kw: ['ขึ้นฉ่าย', 'celery'] },
  mint:          { th: 'ใบมิ้นต์',          en: 'mint',            kw: ['ใบมิ้นต์', 'มิ้นต์', 'สะระแหน่', 'mint'] },
};

// ---------------------------------------------------------------- ตัวเลือกแบบเลือก 1 ค่า (Slot)
// required = ต้องได้ก่อนทวนออเดอร์, short = คำตอบสั้นที่ตีความได้เฉพาะตอนถูกถามเรื่องนั้น
export const GROUPS = {
  // ---------- เบเกอรี
  warm: { th: 'อุ่น', en: 'Warm up', required: true, q: ['อุ่น', 'warm', 'heat'], values: {
    warm:  { th: 'อุ่น', en: 'warmed', extra: 0,
      kw: ['อุ่นให้หน่อย', 'อุ่นให้', 'อุ่นร้อน', 'อุ่น', 'warm it up', 'warmed up', 'heat it up', 'heated', 'warmed', 'warm'], short: ['ได้', 'ใช่', 'yes', 'please', 'sure'] },
    as_is: { th: 'ไม่อุ่น', en: 'not warmed', extra: 0,
      kw: ['ไม่ต้องอุ่น', 'ไม่อุ่น', 'as is', 'no need to warm', 'not warmed', 'room temperature'], short: ['ไม่ต้อง', 'ไม่', 'no', 'no thanks'] },
  } },
  dining: { th: 'ทานที่ร้าน/กลับบ้าน', en: 'For here / to go', required: true, q: ['ทานที่ร้าน', 'กลับบ้าน', 'for here', 'to go', 'take away', 'takeaway'], values: {
    here:     { th: 'ทานที่ร้าน', en: 'for here', extra: 0,
      kw: ['ทานที่ร้าน', 'กินที่ร้าน', 'ทานที่นี่', 'กินที่นี่', 'นั่งทาน', 'for here', 'eat in', 'dine in', 'have it here'], short: ['ที่ร้าน', 'ที่นี่', 'here'] },
    takeaway: { th: 'กลับบ้าน', en: 'to go', extra: 0,
      kw: ['กลับบ้าน', 'ใส่กล่อง', 'ห่อกลับ', 'take away', 'takeaway', 'take-away', 'to go'], short: ['กลับ', 'ห่อ'] },
  } },
  slice: { th: 'แบบชิ้น/ทั้งปอนด์', en: 'Slice / whole', required: true, q: ['ชิ้น', 'ปอนด์', 'slice', 'whole'], values: {
    piece: { th: 'แบบชิ้น', en: 'by the slice', extra: 0,
      kw: ['เป็นชิ้น', 'แบบชิ้น', 'ชิ้นเดียว', 'ชิ้น', 'a slice', 'one slice', 'by the slice', 'slice', 'piece'] },
    whole: { th: 'ทั้งปอนด์', en: 'whole cake (1 lb)', extra: 0,
      kw: ['ทั้งปอนด์', 'ทั้งก้อน', 'เต็มปอนด์', '1 ปอนด์', 'หนึ่งปอนด์', 'ปอนด์', 'the whole cake', 'whole cake', 'whole', '1 pound', 'one pound'] },
  } },
  slicing: { th: 'สไลซ์', en: 'Slicing', required: true, q: ['สไลซ์', 'หั่น', 'slice'], values: {
    sliced:     { th: 'สไลซ์ให้', en: 'sliced', extra: 0, kw: ['สไลซ์ให้', 'หั่นให้', 'หั่นเป็นแผ่น', 'สไลซ์', 'sliced', 'slice it'], short: ['ได้', 'ใช่', 'yes', 'please'] },
    whole_loaf: { th: 'ไม่สไลซ์', en: 'unsliced', extra: 0, kw: ['ไม่ต้องสไลซ์', 'ไม่สไลซ์', 'ไม่ต้องหั่น', 'unsliced', 'whole loaf', 'not sliced'], short: ['ไม่ต้อง', 'ไม่', 'no'] },
  } },

  // ---------- อาหารนานาชาติ
  broth: { th: 'น้ำซุป', en: 'Broth', required: true, q: ['ซุป', 'broth', 'soup'], values: {
    tonkotsu: { th: 'ซุปทงคตสึ', en: 'tonkotsu broth', extra: 0, kw: ['ทงคตสึ', 'ทงคัตสึ', 'ทงคตซึ', 'ซุปกระดูกหมู', 'tonkotsu'] },
    shoyu:    { th: 'ซุปโชยุ',   en: 'shoyu broth',    extra: 0, allergen: 'gluten', kw: ['โชยุ', 'shoyu', 'soy sauce broth'] },
    miso:     { th: 'ซุปมิโสะ',  en: 'miso broth',     extra: 10, kw: ['มิโสะ', 'มิโซะ', 'miso'] },
  } },
  firmness: { th: 'ความนุ่มของเส้น', en: 'Noodle firmness', required: true, q: ['เส้น', 'นุ่ม', 'แข็ง', 'noodle', 'firm'], values: {
    soft:    { th: 'เส้นนิ่ม',  en: 'soft noodles',    extra: 0, kw: ['เส้นนิ่ม', 'เส้นนุ่ม', 'soft noodles', 'yawa'], short: ['นิ่ม', 'นุ่ม', 'soft'] },
    regular: { th: 'เส้นปกติ',  en: 'regular noodles', extra: 0, kw: ['เส้นปกติ', 'regular noodles', 'futsu'], short: ['ปกติ', 'ธรรมดา', 'regular', 'normal'] },
    firm:    { th: 'เส้นแข็ง',  en: 'firm noodles',    extra: 0, kw: ['เส้นแข็ง', 'เส้นเหนียว', 'firm noodles', 'kata', 'al dente'], short: ['แข็ง', 'เหนียว', 'firm', 'hard'] },
  } },
  doneness: { th: 'ความสุก', en: 'Doneness', required: true, q: ['ความสุก', 'สุก', 'how would you like it cooked', 'doneness', 'cooked'], values: {
    rare:        { th: 'แรร์',          en: 'rare',        extra: 0, kw: ['แรร์', 'rare'] },
    medium_rare: { th: 'มีเดียมแรร์',    en: 'medium rare', extra: 0, kw: ['มีเดียมแรร์', 'มีเดี้ยมแรร์', 'มีเดียม แรร์', 'medium rare', 'medium-rare'] },
    medium:      { th: 'มีเดียม',        en: 'medium',      extra: 0, kw: ['มีเดียม', 'มีเดี้ยม', 'สุกปานกลาง', 'medium'], short: ['กลาง'] },
    well_done:   { th: 'สุกมาก (เวลดัน)', en: 'well done',   extra: 0, kw: ['เวลดัน', 'เวลล์ดัน', 'สุกมาก', 'สุกๆ', 'well done', 'well-done'], short: ['สุก'] },
  } },
  pizza_size: { th: 'ขนาดถาด', en: 'Pizza size', required: true, q: ['ถาด', 'นิ้ว', 'ขนาด', 'size'], values: {
    small:  { th: 'ถาดเล็ก 10"', en: 'small (10")',  extra: 0,   kw: ['ถาดเล็ก', '10 นิ้ว', 'small (10")', 'small pizza', '10 inch'], short: ['เล็ก', 'small', 's'] },
    medium: { th: 'ถาดกลาง 12"', en: 'medium (12")', extra: 100, kw: ['ถาดกลาง', '12 นิ้ว', 'medium (12")', 'medium pizza', '12 inch'], short: ['กลาง', 'medium', 'm'] },
    large:  { th: 'ถาดใหญ่ 14"', en: 'large (14")',  extra: 200, kw: ['ถาดใหญ่', '14 นิ้ว', 'large (14")', 'large pizza', '14 inch'], short: ['ใหญ่', 'large', 'l'] },
  } },
  crust: { th: 'แป้ง', en: 'Crust', required: true, q: ['แป้ง', 'ขอบ', 'crust'], values: {
    thin:         { th: 'แป้งบางกรอบ', en: 'thin crust', extra: 0, kw: ['แป้งบาง', 'ขอบบาง', 'บางกรอบ', 'thin crust', 'thin'], short: ['บาง'] },
    thick:        { th: 'แป้งหนานุ่ม', en: 'pan crust', extra: 0, kw: ['แป้งหนา', 'หนานุ่ม', 'pan pizza', 'thick crust', 'thick', 'pan'], short: ['หนา'] },
    cheese_crust: { th: 'ขอบชีส', en: 'cheese-stuffed crust', extra: 79, allergen: 'dairy', kw: ['ขอบชีส', 'ขอบไส้ชีส', 'cheese crust', 'stuffed crust'] },
  } },
  noodle_type: { th: 'ชนิดเส้น', en: 'Pasta', required: true, q: ['เส้น', 'pasta', 'noodle'], values: {
    spaghetti:  { th: 'สปาเก็ตตี้', en: 'spaghetti',  extra: 0, kw: ['สปาเก็ตตี้', 'สปาเกตตี้', 'สปาเก็ตตี', 'spaghetti'] },
    fettuccine: { th: 'เฟตตูชินี่', en: 'fettuccine', extra: 0, kw: ['เฟตตูชินี่', 'เฟตตูชินี', 'fettuccine', 'fettucine'] },
    penne:      { th: 'เพนเน่',     en: 'penne',      extra: 0, kw: ['เพนเน่', 'penne'] },
  } },
  side: { th: 'เครื่องเคียง', en: 'Side', required: true, q: ['เครื่องเคียง', 'ทานคู่', 'side'], values: {
    fries: { th: 'เฟรนช์ฟรายส์', en: 'fries', extra: 0, kw: ['เฟรนช์ฟรายส์', 'เฟรนช์ฟราย', 'เฟรนฟราย', 'มันฝรั่งทอด', 'french fries', 'fries', 'chips'] },
    salad: { th: 'สลัด', en: 'side salad', extra: 0, kw: ['ผักสลัด', 'สลัด', 'side salad', 'salad'] },
    mash:  { th: 'มันบด', en: 'mashed potatoes', extra: 0, allergen: 'dairy', kw: ['มันบด', 'mashed potato', 'mash'] },
  } },
  steak_sauce: { th: 'ซอส', en: 'Sauce', required: true, q: ['ซอส', 'sauce'], values: {
    black_pepper: { th: 'ซอสพริกไทยดำ', en: 'black pepper sauce', extra: 0, kw: ['ซอสพริกไทยดำ', 'พริกไทยดำ', 'black pepper', 'pepper sauce'] },
    mushroom:     { th: 'ซอสเห็ด', en: 'mushroom sauce', extra: 0, allergen: 'dairy', kw: ['ซอสเห็ด', 'เห็ด', 'mushroom'] },
    chimichurri:  { th: 'ซอสชิมิชูร์รี', en: 'chimichurri', extra: 0, kw: ['ชิมิชูร์รี', 'ชิมิ', 'chimichurri'] },
  } },
  carb: { th: 'ทานคู่กับ', en: 'Served with', required: true, q: ['นาน', 'ข้าว', 'naan', 'rice'], values: {
    naan:        { th: 'แป้งนาน', en: 'naan', extra: 0, allergens: ['gluten', 'dairy'], kw: ['แป้งนาน', 'โรตีนาน', 'plain naan', 'naan'], short: ['นาน'] },
    garlic_naan: { th: 'นานกระเทียม', en: 'garlic naan', extra: 20, allergens: ['gluten', 'dairy'], kw: ['นานกระเทียม', 'garlic naan'] },
    rice:        { th: 'ข้าวบาสมาติ', en: 'basmati rice', extra: 0, kw: ['ข้าวบาสมาติ', 'บาสมาติ', 'ข้าวสวย', 'basmati', 'rice'], short: ['ข้าว'] },
  } },
  protein: { th: 'เนื้อสัตว์', en: 'Protein', required: true, q: ['เนื้อสัตว์', 'protein', 'meat'], values: {
    beef:    { th: 'เนื้อวัว', en: 'beef',    extra: 30, kw: ['เนื้อวัว', 'บุลโกกิ', 'เนื้อ', 'bulgogi', 'beef'] },
    chicken: { th: 'ไก่',      en: 'chicken', extra: 0,  kw: ['ไก่', 'chicken'] },
    tofu:    { th: 'เต้าหู้',   en: 'tofu',    extra: 0,  kw: ['เต้าหู้', 'tofu'] },
  } },
  spice: { th: 'ความเผ็ด', en: 'Spice level', required: true, q: ['เผ็ด', 'spicy', 'spice'], values: {
    none:   { th: 'ไม่เผ็ด',  en: 'not spicy',    extra: 0, kw: ['ไม่เผ็ด', 'ไม่ใส่พริก', 'not spicy', 'no chili', 'no spice', 'non-spicy', 'mild please'], short: ['none', 'ไม่เลย'] },
    mild:   { th: 'เผ็ดน้อย', en: 'mild',         extra: 0, kw: ['เผ็ดน้อย', 'เผ็ดนิดหน่อย', 'เผ็ดนิด', 'a little spicy', 'slightly spicy', 'mild'], short: ['น้อย', 'นิดหน่อย', 'a little', 'little'] },
    medium: { th: 'เผ็ดกลาง', en: 'medium spicy', extra: 0, kw: ['เผ็ดกลาง', 'เผ็ดปกติ', 'medium spicy', 'normal spicy'], short: ['กลาง', 'ปกติ', 'เผ็ด', 'normal', 'spicy'] },
    hot:    { th: 'เผ็ดมาก',  en: 'very spicy',   extra: 0, kw: ['เผ็ดมาก', 'เผ็ดๆ', 'เผ็ดจัด', 'very spicy', 'extra spicy', 'super spicy'], short: ['มาก', 'จัด', 'very'] },
  } },

  // ---------- น้ำผลไม้ / มัทฉะ
  temperature: { th: 'ร้อน/เย็น/ปั่น', en: 'Hot/iced/frappé', required: true, q: ['ร้อน', 'เย็น', 'ปั่น', 'hot', 'iced', 'cold'], values: {
    hot:    { th: 'ร้อน', en: 'hot',    extra: 0,  kw: ['ร้อน', 'hot', 'warm'] },
    iced:   { th: 'เย็น', en: 'iced',   extra: 0,  kw: ['เย็น', 'iced', 'cold'] },
    frappe: { th: 'ปั่น', en: 'frappé', extra: 15, kw: ['ปั่น', 'frappe', 'frappé', 'blended'] },
  } },
  milk: { th: 'นม', en: 'Milk', required: true, q: ['นม', 'milk'], values: {
    dairy:  { th: 'นมวัว',        en: 'dairy milk',  extra: 0,  allergen: 'dairy', kw: ['นมวัว', 'นมสด', 'dairy milk', 'whole milk', 'fresh milk', 'regular milk'], short: ['ปกติ', 'ธรรมดา', 'normal', 'regular', 'dairy'] },
    oat:    { th: 'นมโอ๊ต',       en: 'oat milk',    extra: 15, kw: ['นมโอ๊ต', 'นมโอ๊ท', 'โอ๊ต', 'oat milk', 'oat'] },
    soy:    { th: 'นมถั่วเหลือง', en: 'soy milk',    extra: 10, kw: ['นมถั่วเหลือง', 'ถั่วเหลือง', 'โซย่า', 'soy milk', 'soy'] },
    almond: { th: 'นมอัลมอนด์',   en: 'almond milk', extra: 15, allergen: 'tree_nut', kw: ['นมอัลมอนด์', 'almond milk'] },
  } },
  sweetness: { th: 'ความหวาน', en: 'Sweetness', required: true, q: ['หวาน', 'น้ำตาล', 'sweet', 'sugar'], values: {
    none:   { th: 'ไม่หวาน',  en: 'no sugar', extra: 0, kw: ['ไม่หวาน', 'หวาน 0', 'หวาน0', 'ไม่ใส่น้ำตาล', 'ไม่ใส่น้ำเชื่อม', 'no sugar', 'unsweetened', 'sugar free', 'sugar-free', 'without sugar', 'not sweet', 'no syrup'], short: ['ศูนย์', 'no', 'none', 'zero'] },
    less:   { th: 'หวานน้อย', en: 'less sweet', extra: 0, kw: ['หวานน้อย', 'หวาน 50', 'หวานครึ่ง', 'หวานนิด', 'less sweet', 'less sugar', 'half sweet', 'half sugar', 'slightly sweet'], short: ['น้อย', 'นิดเดียว', 'ครึ่ง', 'less', 'half', 'a little'] },
    normal: { th: 'หวานปกติ', en: 'normal sweetness', extra: 0, kw: ['หวานปกติ', 'หวานกลาง', 'หวาน 100', 'หวานธรรมดา', 'normal sweetness', 'regular sweetness', 'normal sweet', 'regular sweet', 'normal sugar'], short: ['ปกติ', 'ธรรมดา', 'กลาง', 'หวาน', 'normal', 'regular', 'sweet'] },
    extra:  { th: 'หวานมาก',  en: 'extra sweet', extra: 0, kw: ['หวานมาก', 'หวานๆ', 'หวานเพิ่ม', 'หวานจัด', 'extra sweet', 'extra sugar', 'very sweet', 'sweeter'], short: ['มาก', 'เยอะ', 'extra', 'more', 'very'] },
  } },
  size: { th: 'ไซส์', en: 'Size', required: true, q: ['ไซส์', 'ขนาด', 'size'], values: {
    regular: { th: 'ไซส์ปกติ', en: 'regular size', extra: 0,  kw: ['ไซส์ปกติ', 'ขนาดปกติ', 'แก้วปกติ', 'ไซส์เล็ก', 'แก้วเล็ก', '16 ออนซ์', 'regular size', 'normal size', 'small'], short: ['ปกติ', 'ธรรมดา', 'เล็ก', 'm', 'regular', 'normal', 'medium'] },
    large:   { th: 'ไซส์ใหญ่', en: 'large size',   extra: 15, kw: ['ไซส์ใหญ่', 'แก้วใหญ่', 'ใหญ่', '22 ออนซ์', 'large', 'big'], short: ['l'] },
  } },
  ice: { th: 'น้ำแข็ง', en: 'Ice', required: true, q: ['น้ำแข็ง', 'ice'], values: {
    normal: { th: 'น้ำแข็งปกติ', en: 'regular ice', extra: 0, kw: ['น้ำแข็งปกติ', 'regular ice', 'normal ice'], short: ['ปกติ', 'ธรรมดา', 'normal', 'regular'] },
    less:   { th: 'น้ำแข็งน้อย', en: 'light ice',   extra: 0, kw: ['น้ำแข็งน้อย', 'น้ำแข็งนิดเดียว', 'less ice', 'light ice', 'little ice'], short: ['น้อย', 'นิดเดียว', 'less', 'little'] },
    none:   { th: 'ไม่ใส่น้ำแข็ง', en: 'no ice',    extra: 0, kw: ['ไม่ใส่น้ำแข็ง', 'ไม่เอาน้ำแข็ง', 'ไม่ต้องใส่น้ำแข็ง', 'no ice', 'without ice'], short: ['ไม่ใส่', 'ไม่เอา', 'none', 'no'] },
  } },
  base: { th: 'เบสสมูทตี้', en: 'Smoothie base', required: true, q: ['โยเกิร์ต', 'เบส', 'base', 'yogurt'], values: {
    yogurt:   { th: 'โยเกิร์ต', en: 'yogurt', extra: 0, allergen: 'dairy', kw: ['โยเกิร์ต', 'yogurt', 'yoghurt'] },
    coconut:  { th: 'น้ำมะพร้าว', en: 'coconut water', extra: 10, kw: ['น้ำมะพร้าว', 'มะพร้าว', 'coconut water', 'coconut'] },
    fruit:    { th: 'ผลไม้ล้วน', en: 'fruit only', extra: 0, kw: ['ผลไม้ล้วน', 'ไม่ใส่นม', 'ไม่ใส่โยเกิร์ต', 'fruit only', 'just fruit'] },
  } },
  matcha_level: { th: 'ความเข้มมัทฉะ', en: 'Matcha strength', required: true, q: ['เข้ม', 'strong', 'strength'], values: {
    standard: { th: 'มัทฉะปกติ', en: 'standard matcha', extra: 0, kw: ['มัทฉะปกติ', 'เข้มปกติ', 'regular matcha', 'standard matcha'], short: ['ปกติ', 'ธรรมดา', 'normal', 'regular', 'standard'] },
    strong:   { th: 'มัทฉะเข้มข้น', en: 'strong matcha', extra: 20, kw: ['มัทฉะเข้มข้น', 'เข้มข้น', 'เข้มๆ', 'เข้ม ๆ', 'เข้ม', 'strong matcha', 'stronger', 'strong'] },
    double:   { th: 'ดับเบิ้ลมัทฉะ', en: 'double matcha', extra: 40, kw: ['ดับเบิ้ลมัทฉะ', 'เข้มพิเศษ', 'เข้มสุด', 'double matcha', 'extra strong'] },
  } },

  // ---------- ค็อกเทล / ม็อกเทล
  alcohol: { th: 'แอลกอฮอล์', en: 'Alcohol', required: true, q: ['แอลกอฮอล์', 'แอล', 'เวอร์จิ้น', 'alcohol', 'virgin'], values: {
    with:   { th: 'แบบมีแอลกอฮอล์', en: 'with alcohol', extra: 90,
      kw: ['ใส่แอลกอฮอล์', 'มีแอลกอฮอล์', 'แบบมีแอล', 'ใส่เหล้า', 'with alcohol', 'alcoholic', 'with rum', 'with tequila', 'รัม', 'เตกีล่า', 'rum', 'tequila'], short: ['มี', 'ใส่', 'with', 'yes'] },
    virgin: { th: 'เวอร์จิ้น (ไม่มีแอลกอฮอล์)', en: 'virgin (alcohol-free)', extra: 0,
      kw: ['เวอร์จิ้น', 'เวอร์จิน', 'ไม่มีแอลกอฮอล์', 'ไม่ใส่แอลกอฮอล์', 'ไม่เอาแอลกอฮอล์', 'ไม่ใส่เหล้า', 'ไม่มีแอล', 'virgin', 'non-alcoholic', 'non alcoholic', 'alcohol-free', 'alcohol free', 'no alcohol', 'without alcohol'],
      short: ['ไม่มี', 'ไม่ใส่', 'ไม่', 'no', 'without'] },
  } },
  rim: { th: 'ขอบแก้ว', en: 'Rim', required: true, q: ['ขอบ', 'rim'], values: {
    salt:      { th: 'ขอบเกลือ', en: 'salt rim', extra: 0, kw: ['ขอบเกลือ', 'เกลือ', 'salt rim', 'salted rim', 'salt'] },
    sugar_rim: { th: 'ขอบน้ำตาล', en: 'sugar rim', extra: 0, kw: ['ขอบน้ำตาล', 'sugar rim', 'sugared rim'] },
    no_rim:    { th: 'ไม่ทำขอบ', en: 'no rim', extra: 0, kw: ['ไม่เอาขอบ', 'ไม่ต้องทำขอบ', 'ไม่ทำขอบ', 'ขอบเปล่า', 'no rim', 'without rim', 'plain rim'], short: ['ไม่เอา', 'ไม่ต้อง', 'no'] },
  } },
  serve: { th: 'แบบเสิร์ฟ', en: 'Serve', required: true, q: ['ร็อค', 'ปั่น', 'rocks', 'frozen'], values: {
    rocks:  { th: 'ใส่น้ำแข็ง (On the rocks)', en: 'on the rocks', extra: 0, kw: ['ออนเดอะร็อค', 'ออนเดอะร็อก', 'on the rocks', 'ใส่น้ำแข็ง', 'rocks'] },
    frozen: { th: 'ปั่น (Frozen)', en: 'frozen', extra: 10, kw: ['ปั่น', 'frozen', 'blended'] },
  } },
  garnish: { th: 'ของตกแต่ง', en: 'Garnish', required: true, q: ['ตกแต่ง', 'garnish'], values: {
    lime:       { th: 'มะนาว', en: 'lime', extra: 0, kw: ['มะนาว', 'lime'] },
    cucumber:   { th: 'แตงกวา', en: 'cucumber', extra: 0, kw: ['แตงกวา', 'cucumber'] },
    grapefruit: { th: 'เกรปฟรุต', en: 'grapefruit', extra: 0, kw: ['เกรปฟรุต', 'grapefruit'] },
  } },
};

// ---------------------------------------------------------------- Checkbox: คำขอพิเศษ / ของเพิ่ม ("ไม่ใส่..." สร้างอัตโนมัติ = no_<ingredient>)
export const MODIFIERS = {
  // เบเกอรี
  ice_cream:   { type: 'addon', emoji: '🍨', th: 'ไอศกรีมวานิลลา 1 สกู๊ป', en: 'a scoop of vanilla ice cream', extra: 35, allergens: ['dairy', 'egg'],
    kw: ['ไอศกรีม', 'ไอติม', 'ice cream'], applies: (it) => !!(it.pastry || it.cake) },
  whipped:     { type: 'addon', th: 'วิปครีม', en: 'whipped cream', extra: 15, allergens: ['dairy'],
    kw: ['วิปครีม', 'วิป', 'whipped cream'], applies: (it) => !!(it.pastry || it.cake || it.matcha) },
  candle:      { type: 'addon', emoji: '🕯️', th: 'เทียนวันเกิด', en: 'birthday candle', extra: 10,
    kw: ['เทียนวันเกิด', 'เทียน', 'birthday candle', 'candle'], applies: (it) => !!it.cake },
  gift_box:    { type: 'request', emoji: '🎁', th: 'ใส่กล่องของขวัญ', en: 'gift box', extra: 25,
    kw: ['กล่องของขวัญ', 'ห่อของขวัญ', 'gift box', 'gift wrap', 'as a gift'], applies: (it) => it.kind === 'bakery' },
  butter_side: { type: 'addon', th: 'เนยสดแยก', en: 'butter on the side', extra: 15, allergens: ['dairy'],
    kw: ['เนยแยก', 'ขอเนย', 'butter on the side', 'side of butter'], applies: (it) => !!it.bread },
  // อาหารนานาชาติ
  ajitama:      { type: 'addon', emoji: '🥚', th: 'ไข่ต้มยางมะตูม (อาจิทามะ)', en: 'ramen egg (ajitama)', extra: 25, allergens: ['egg'],
    kw: ['ไข่ต้มยางมะตูม', 'ไข่ยางมะตูม', 'ไข่ทรงเครื่อง', 'อาจิทามะ', 'ajitama', 'ramen egg', 'soft boiled egg', 'marinated egg'], applies: (it) => !!it.ramen },
  extra_chashu: { type: 'addon', th: 'เพิ่มชาชู', en: 'extra chashu', extra: 45, kw: ['เพิ่มชาชู', 'ชาชูเพิ่ม', 'extra chashu', 'more chashu'], applies: (it) => !!it.ramen },
  kaedama:      { type: 'addon', th: 'เพิ่มเส้น (คาเอดามะ)', en: 'extra noodles (kaedama)', extra: 30, allergens: ['gluten'],
    kw: ['เพิ่มเส้น', 'คาเอดามะ', 'kaedama', 'extra noodles'], applies: (it) => !!it.ramen },
  add_bacon:    { type: 'addon', th: 'เพิ่มเบคอน', en: 'add bacon', extra: 35, kw: ['เพิ่มเบคอน', 'ใส่เบคอน', 'add bacon', 'extra bacon', 'with bacon'], applies: (it) => !!it.burger },
  extra_cheese: { type: 'addon', th: 'เพิ่มชีส', en: 'extra cheese', extra: 30, allergens: ['dairy'],
    kw: ['เพิ่มชีส', 'ชีสเพิ่ม', 'extra cheese', 'double cheese'], applies: (it) => !!(it.burger || it.pizza) },
  sauce_side:   { type: 'request', th: 'แยกซอส', en: 'sauce on the side', extra: 0,
    kw: ['แยกซอส', 'ซอสแยก', 'sauce on the side', 'sauce separately'], applies: (it) => !!it.sauce },
  // น้ำผลไม้ / มัทฉะ
  boba:          { type: 'addon', emoji: '⚫', th: 'เพิ่มไข่มุก', en: 'boba pearls', extra: 15, kw: ['ไข่มุก', 'boba', 'tapioca pearls', 'pearls'], applies: (it) => it.kind === 'drink' },
  chia:          { type: 'addon', th: 'เพิ่มเมล็ดเจีย', en: 'chia seeds', extra: 15, kw: ['เมล็ดเจีย', 'เจีย', 'chia'], applies: (it) => !!it.juice },
  coconut_jelly: { type: 'addon', th: 'เพิ่มวุ้นมะพร้าว', en: 'coconut jelly', extra: 15, kw: ['วุ้นมะพร้าว', 'วุ้น', 'nata de coco', 'coconut jelly'], applies: (it) => it.kind === 'drink' },
  honey:         { type: 'request', emoji: '🍯', th: 'ใช้น้ำผึ้งแทนน้ำตาล', en: 'honey instead of sugar', extra: 10,
    kw: ['น้ำผึ้ง', 'honey'], applies: (it) => it.groups?.includes('sweetness') },
  // ค็อกเทล / ม็อกเทล
  double_shot: { type: 'addon', th: 'ดับเบิ้ลช็อต', en: 'double shot', extra: 90, alcohol: true,
    kw: ['ดับเบิ้ลช็อต', 'ดับเบิ้ล', 'double shot', 'make it a double', 'double'], applies: (it) => !!(it.alcoholic || it.groups?.includes('alcohol')) },
  no_straw:    { type: 'request', emoji: '🌱', th: 'ไม่รับหลอด', en: 'no straw', extra: 0,
    kw: ['ไม่รับหลอด', 'ไม่เอาหลอด', 'ไม่ใช้หลอด', 'no straw', 'without a straw'], applies: (it) => it.kind === 'drink' },
  takeaway:    { type: 'request', th: 'สั่งกลับบ้าน', en: 'takeaway', extra: 5,
    kw: ['ใส่แก้วกลับบ้าน', 'กลับบ้าน', 'ใส่กล่อง', 'take away', 'takeaway', 'to go'], applies: () => true },
};

// ---------------------------------------------------------------- เมนู
const BAKERY_MENU = [
  { id: 'bk_01', th: 'ครัวซองต์เนยสด', en: 'Butter Croissant', emoji: '🥐', kind: 'bakery', pastry: true, price: 65, prep: 3,
    keywords: ['ครัวซองต์เนยสด', 'ครัวซองต์เนย', 'ครัวซองต์', 'ครัวซอง', 'butter croissant', 'plain croissant', 'croissant'],
    groups: ['warm', 'dining'], fixed: ['butter', 'wheat_flour', 'egg'] },
  { id: 'bk_02', th: 'ครัวซองต์อัลมอนด์', en: 'Almond Croissant', emoji: '🥐', kind: 'bakery', pastry: true, price: 85, prep: 3,
    keywords: ['ครัวซองต์อัลมอนด์', 'ครัวซองอัลมอนด์', 'almond croissant'],
    groups: ['warm', 'dining'], fixed: ['butter', 'wheat_flour', 'egg', 'almond'] },
  { id: 'bk_03', th: 'เพน โอ ช็อกโกแลต', en: 'Pain au Chocolat', emoji: '🍫', kind: 'bakery', pastry: true, price: 75, prep: 3,
    keywords: ['เพน โอ ช็อกโกแลต', 'เพนโอช็อกโกแลต', 'ครัวซองต์ช็อกโกแลต', 'pain au chocolat', 'chocolate croissant'],
    groups: ['warm', 'dining'], fixed: ['butter', 'wheat_flour'] },
  { id: 'bk_04', th: 'ชีสเค้กบลูเบอร์รี่', en: 'Blueberry Cheesecake', emoji: '🍰', kind: 'bakery', cake: true, price: 110, prep: 2,
    keywords: ['ชีสเค้กบลูเบอร์รี่', 'ชีสเค้ก', 'บลูเบอร์รี่ชีสเค้ก', 'blueberry cheesecake', 'cheesecake'],
    groups: ['slice', 'dining'], extras: { slice: { whole: 780 } }, fixed: ['cream_cheese', 'wheat_flour', 'egg'] },
  { id: 'bk_05', th: 'บราวนี่วอลนัท', en: 'Walnut Brownie', emoji: '🟫', kind: 'bakery', pastry: true, price: 69, prep: 2,
    keywords: ['บราวนี่วอลนัท', 'บราวนี่', 'บราวนี', 'walnut brownie', 'brownie'],
    groups: ['warm', 'dining'], fixed: ['butter', 'egg', 'wheat_flour', 'walnut'] },
  { id: 'bk_06', th: 'ซินนามอนโรล', en: 'Cinnamon Roll', emoji: '🌀', kind: 'bakery', pastry: true, price: 79, prep: 3,
    keywords: ['ซินนามอนโรล', 'ชินนาม่อนโรล', 'ซินนาม่อนโรล', 'cinnamon roll', 'cinnamon bun'],
    groups: ['warm', 'dining'], fixed: ['butter', 'wheat_flour', 'egg'], removable: ['icing'] },
  { id: 'bk_07', th: 'เค้กช็อกโกแลตฟัดจ์', en: 'Chocolate Fudge Cake', emoji: '🎂', kind: 'bakery', cake: true, price: 120, prep: 2,
    keywords: ['เค้กช็อกโกแลตฟัดจ์', 'เค้กช็อกโกแลต', 'เค้กช็อคโกแลต', 'เค้กวันเกิด', 'chocolate fudge cake', 'chocolate cake', 'birthday cake'],
    groups: ['slice', 'dining'], extras: { slice: { whole: 880 } }, fixed: ['butter', 'egg', 'wheat_flour'] },
  { id: 'bk_08', th: 'ขนมปังซาวร์โดว์', en: 'Sourdough Loaf', emoji: '🍞', kind: 'bakery', bread: true, price: 180, prep: 2,
    keywords: ['ขนมปังซาวร์โดว์', 'ซาวร์โดว์', 'ซาวโดว์', 'sourdough loaf', 'sourdough'],
    groups: ['slicing', 'dining'], fixed: ['wheat_flour'] },
];

const INTL_MENU = [
  { id: 'in_01', th: 'ราเมงชาชู', en: 'Chashu Ramen', emoji: '🍜', kind: 'food', ramen: true, price: 189, prep: 10,
    keywords: ['ราเมงชาชู', 'ราเมน', 'ราเมง', 'ราเม็ง', 'chashu ramen', 'ramen'],
    groups: ['broth', 'firmness'], fixed: ['wheat_noodle'], removable: ['spring_onion', 'bamboo_shoot', 'bean_sprout'] },
  { id: 'in_02', th: 'พิซซ่ามาร์การิต้า', en: 'Margherita Pizza', emoji: '🍕', kind: 'food', pizza: true, price: 259, prep: 15,
    keywords: ['พิซซ่ามาร์การิต้า', 'มาร์การิต้าพิซซ่า', 'พิซซ่า', 'margherita pizza', 'margherita', 'pizza'],
    groups: ['pizza_size', 'crust'], fixed: ['cheese', 'wheat_flour'], removable: ['basil'] },
  { id: 'in_03', th: 'คาโบนาร่า', en: 'Carbonara', emoji: '🍝', kind: 'food', price: 219, prep: 12,
    keywords: ['คาโบนาร่า', 'คาร์โบนาร่า', 'carbonara', 'pasta'],
    groups: ['noodle_type'], fixed: ['egg', 'cheese', 'wheat_flour'], removable: ['bacon'] },
  { id: 'in_04', th: 'เบอร์เกอร์เนื้อ', en: 'Beef Burger', emoji: '🍔', kind: 'food', burger: true, price: 249, prep: 12,
    keywords: ['เบอร์เกอร์เนื้อ', 'แฮมเบอร์เกอร์', 'เบอร์เกอร์', 'beef burger', 'hamburger', 'cheeseburger', 'burger'],
    groups: ['doneness', 'side'], fixed: ['bun'], removable: ['cheese', 'pickles', 'onion', 'tomato', 'mayo'] },
  { id: 'in_05', th: 'สเต๊กริบอาย', en: 'Ribeye Steak', emoji: '🥩', kind: 'food', sauce: true, price: 590, prep: 18,
    keywords: ['สเต๊กริบอาย', 'ริบอาย', 'สเต๊กเนื้อ', 'สเต็ก', 'สเต๊ก', 'ribeye steak', 'ribeye', 'steak'],
    groups: ['doneness', 'steak_sauce', 'side'] },
  { id: 'in_06', th: 'บัตเตอร์ชิคเก้น', en: 'Butter Chicken', emoji: '🍛', kind: 'food', price: 229, prep: 12,
    keywords: ['บัตเตอร์ชิคเก้น', 'บัตเตอร์ชิกเก้น', 'แกงไก่อินเดีย', 'แกงอินเดีย', 'butter chicken', 'chicken curry', 'curry'],
    groups: ['spice', 'carb'], fixed: ['cream'], removable: ['coriander'] },
  { id: 'in_07', th: 'บิบิมบับ', en: 'Bibimbap', emoji: '🍚', kind: 'food', price: 199, prep: 10,
    keywords: ['บิบิมบับ', 'บิบิมบัพ', 'ข้าวยำเกาหลี', 'bibimbap'],
    groups: ['protein', 'spice'], removable: ['egg', 'bean_sprout', 'gochujang'] },
];

const JUICE_MENU = [
  { id: 'jm_01', th: 'น้ำส้มคั้นสด', en: 'Fresh Orange Juice', emoji: '🍊', kind: 'drink', juice: true, price: 65, prep: 3,
    keywords: ['น้ำส้มคั้นสด', 'น้ำส้มคั้น', 'น้ำส้ม', 'fresh orange juice', 'orange juice', 'oj'],
    groups: ['ice', 'sweetness', 'size'] },
  { id: 'jm_02', th: 'แตงโมปั่น', en: 'Watermelon Smoothie', emoji: '🍉', kind: 'drink', juice: true, price: 60, prep: 3,
    keywords: ['แตงโมปั่น', 'น้ำแตงโม', 'แตงโม', 'watermelon smoothie', 'watermelon juice', 'watermelon'],
    groups: ['sweetness', 'size'] },
  { id: 'jm_03', th: 'สมูทตี้มะม่วง', en: 'Mango Smoothie', emoji: '🥭', kind: 'drink', juice: true, price: 75, prep: 4,
    keywords: ['สมูทตี้มะม่วง', 'มะม่วงปั่น', 'มะม่วง', 'mango smoothie', 'mango'],
    groups: ['base', 'sweetness', 'size'] },
  { id: 'jm_04', th: 'กรีนดีท็อกซ์', en: 'Green Detox Juice', emoji: '🥬', kind: 'drink', juice: true, price: 85, prep: 4,
    keywords: ['กรีนดีท็อกซ์', 'น้ำผักสีเขียว', 'น้ำผัก', 'ดีท็อกซ์', 'green detox', 'green juice', 'detox'],
    groups: ['ice', 'size'], removable: ['ginger', 'celery'] },
  { id: 'jm_05', th: 'มัทฉะลาเต้', en: 'Matcha Latte', emoji: '🍵', kind: 'drink', matcha: true, price: 95, prep: 4,
    keywords: ['มัทฉะลาเต้', 'มัทฉะลาเต', 'ชาเขียวลาเต้', 'matcha latte'],
    groups: ['temperature', 'milk', 'sweetness', 'matcha_level'], values: { temperature: ['hot', 'iced', 'frappe'] } },
  { id: 'jm_06', th: 'มัทฉะเพียว', en: 'Pure Matcha', emoji: '🍵', kind: 'drink', matcha: true, price: 90, prep: 4,
    keywords: ['มัทฉะเพียว', 'มัทฉะใส', 'มัทฉะ', 'มัชฉะ', 'pure matcha', 'usucha', 'matcha'],
    groups: ['temperature', 'sweetness', 'matcha_level'], values: { temperature: ['hot', 'iced'] } },
  { id: 'jm_07', th: 'มัทฉะยูซุโซดา', en: 'Matcha Yuzu Soda', emoji: '🍋', kind: 'drink', matcha: true, price: 110, prep: 4,
    keywords: ['มัทฉะยูซุโซดา', 'มัทฉะยูซุ', 'ยูซุ', 'matcha yuzu soda', 'yuzu'],
    groups: ['ice', 'sweetness'] },
];

const BAR_MENU = [
  { id: 'bar_01', th: 'โมจิโต้', en: 'Mojito', emoji: '🍃', kind: 'drink', price: 150, prep: 5,
    keywords: ['โมจิโต้', 'โมฮิโต้', 'โมจิโต', 'mojito'], groups: ['alcohol', 'sweetness'] },
  { id: 'bar_02', th: 'มาร์การิต้า', en: 'Margarita', emoji: '🍸', kind: 'drink', price: 160, prep: 5,
    keywords: ['มาร์การิต้า', 'มาการิต้า', 'margarita'], groups: ['alcohol', 'serve', 'rim'] },
  { id: 'bar_03', th: 'พีน่าโคลาด้า', en: 'Piña Colada', emoji: '🍍', kind: 'drink', price: 160, prep: 5,
    keywords: ['พีน่าโคลาด้า', 'พินาโคลาดา', 'พิน่าโคลาด้า', 'piña colada', 'pina colada'], groups: ['alcohol'] },
  { id: 'bar_04', th: 'จินโทนิค', en: 'Gin & Tonic', emoji: '🥃', kind: 'drink', alcoholic: true, price: 240, prep: 3,
    keywords: ['จินโทนิค', 'จินโทนิก', 'จินแอนด์โทนิค', 'gin and tonic', 'gin & tonic', 'gin tonic', 'g&t'], groups: ['garnish'] },
  { id: 'bar_05', th: 'อัญชันมะนาวโซดา', en: 'Butterfly Pea Lemonade', emoji: '💜', kind: 'drink', price: 95, prep: 3,
    keywords: ['อัญชันมะนาวโซดา', 'อัญชันมะนาว', 'อัญชัน', 'butterfly pea lemonade', 'butterfly pea'], groups: ['sweetness', 'ice'] },
  { id: 'bar_06', th: 'เชอร์ลีย์ เทมเปิล', en: 'Shirley Temple', emoji: '🍒', kind: 'drink', price: 90, prep: 3,
    keywords: ['เชอร์ลีย์ เทมเปิล', 'เชอร์ลีย์เทมเปิล', 'เชอร์ลี่ย์', 'shirley temple'], groups: ['ice'] },
  { id: 'bar_07', th: 'แพชชั่นฟรุตฟิซ', en: 'Passion Fruit Fizz', emoji: '🥂', kind: 'drink', price: 95, prep: 3,
    keywords: ['แพชชั่นฟรุตฟิซ', 'แพชชั่นฟรุต', 'เสาวรสโซดา', 'เสาวรส', 'passion fruit fizz', 'passion fruit'], groups: ['sweetness', 'ice'] },
];

// ---------------------------------------------------------------- สถานการณ์ (Scenario 2.1 - 2.4)
export const SCENARIOS = {
  bakery: {
    id: 'bakery', code: '2.1', icon: '🥐', th: 'ร้านเบเกอรี', en: 'Bakery',
    staff: { th: 'พนักงานร้านเบเกอรี', en: 'Bakery staff', emoji: '👩‍🍳' },
    customer: { emoji: '🧑' },
    unit: { th: 'ชิ้น', en: 'piece' },
    decor: '🥐 🥖 🍰 🧁 🍪 🥐',
    focus: { th: 'ตอบคำถามปลายเปิด (อุ่นไหม / ทานที่ร้านไหม) + สั่งเค้กวันเกิด', en: 'Answer quick questions (warm it up? for here?) + order a birthday cake' },
    tip: { th: 'ครั้งหน้าลองบอกเมนู อุ่นหรือไม่ และทานที่ร้าน/กลับบ้าน ในประโยคเดียว', en: 'Next time, say the item, warm or not, and for here/to go in one sentence' },
    recapExample: { th: '"ครัวซองต์อัลมอนด์ อุ่น ทานที่ร้านนะคะ"', en: '"One almond croissant, warmed, for here, right?"' },
    menu: BAKERY_MENU,
    modifiers: ['ice_cream', 'whipped', 'candle', 'gift_box', 'butter_side'],
    generic: [
      { key: 'cake', th: 'เค้ก', en: 'cakes', kw: ['เค้ก', 'cake'], filter: (it) => !!it.cake },
      { key: 'pastry', th: 'ขนม', en: 'pastries', kw: ['ขนมปัง', 'ขนม', 'pastry', 'bread', 'something sweet'], filter: (it) => !!(it.pastry || it.bread) },
    ],
    opening: { th: 'สวัสดีค่ะ ยินดีต้อนรับค่ะ ขนมเพิ่งออกจากเตาเลยค่ะ รับอะไรดีคะ?', en: 'Hi, welcome! Everything just came out of the oven — what can I get you?' },
    askItem: { th: 'รับขนมตัวไหนดีคะ?', en: 'Which one would you like?' },
    recommend: { th: 'ครัวซองต์อัลมอนด์อุ่นๆ ขายดีที่สุดค่ะ ถ้าเป็นวันเกิดแนะนำเค้กช็อกโกแลตฟัดจ์ทั้งปอนด์ค่ะ', en: 'The warm almond croissant is our best seller; for a birthday, try a whole chocolate fudge cake.' },
    polite: 'ค่ะ',
    missions: [
      { id: 'b1', th: 'ครัวซองต์อุ่นๆ', en: 'Warm Croissant',
        brief: { th: 'สั่งครัวซองต์อัลมอนด์ อุ่นให้ ทานที่ร้าน พร้อมไอศกรีม 1 สกู๊ป', en: 'Order an almond croissant, warmed, for here, with a scoop of ice cream' },
        target: { item: 'bk_02', options: { warm: 'warm', dining: 'here' }, modifiers: ['ice_cream'], quantity: 1 } },
      { id: 'b2', th: 'เค้กวันเกิดเพื่อน', en: "Friend's Birthday Cake",
        brief: { th: 'สั่งเค้กช็อกโกแลตฟัดจ์ทั้งปอนด์ กลับบ้าน ขอเทียนวันเกิดและกล่องของขวัญ', en: 'Order a whole chocolate fudge cake to go, with a birthday candle and a gift box' },
        target: { item: 'bk_07', options: { slice: 'whole', dining: 'takeaway' }, modifiers: ['candle', 'gift_box'], quantity: 1 } },
      { id: 'b3', th: 'แพ้ถั่วเปลือกแข็ง', en: 'Tree-nut Allergy', profile: { allergies: ['tree_nut'] },
        brief: { th: 'คุณแพ้ถั่วเปลือกแข็ง (อัลมอนด์ วอลนัท) อยากได้ขนมอุ่นๆ ทานที่ร้าน — แจ้งพนักงานและเลือกให้ปลอดภัย', en: 'You are allergic to tree nuts. Get a warm pastry for here — tell the staff and choose safely' },
        target: { options: { warm: 'warm', dining: 'here' }, quantity: 1 } },
      { id: 'b4', th: 'ชีสเค้กกลับบ้าน', en: 'Cheesecake to Go',
        brief: { th: 'สั่งชีสเค้กบลูเบอร์รี่ 2 ชิ้น กลับบ้าน', en: 'Order 2 slices of blueberry cheesecake to go' },
        target: { item: 'bk_04', options: { slice: 'piece', dining: 'takeaway' }, quantity: 2 } },
      { id: 'b5', th: 'แพ้นมและไข่', en: 'No Dairy, No Eggs', profile: { allergies: ['dairy', 'egg'] },
        brief: { th: 'คุณแพ้นมวัวและไข่ ลองถามพนักงานว่ามีอะไรทานได้ แล้วสั่งกลับบ้าน (สไลซ์ให้ด้วย)', en: 'You are allergic to dairy and eggs. Ask what you can eat, then order it to go (sliced)' },
        target: { item: 'bk_08', options: { slicing: 'sliced', dining: 'takeaway' }, quantity: 1 } },
    ],
  },

  international: {
    id: 'international', code: '2.2', icon: '🌏', th: 'อาหารนานาชาติ', en: 'International Food',
    staff: { th: 'พนักงานเสิร์ฟ', en: 'Server', emoji: '🧑‍🍳' },
    customer: { emoji: '🧑' },
    unit: { th: 'จาน', en: 'plate' },
    decor: '🍜 🍕 🍔 🥩 🍛 🍚',
    focus: { th: 'ศัพท์เฉพาะของแต่ละชาติ: ความสุกสเต๊ก, ซุปและเส้นราเมง, ขนาดพิซซ่า, ความเผ็ดแกงอินเดีย', en: 'Cuisine-specific terms: steak doneness, ramen broth & noodles, pizza size, curry spice' },
    tip: { th: 'ครั้งหน้าลองบอกรายละเอียดเฉพาะของเมนูไปพร้อมกัน เช่น "สเต๊กมีเดียมแรร์ ซอสพริกไทยดำ กับสลัด"', en: 'Next time give the details together, e.g. "ribeye medium rare, pepper sauce, with salad"' },
    recapExample: { th: '"ราเมงซุปทงคตสึ เส้นแข็ง เพิ่มไข่ ไม่ใส่ต้นหอมนะครับ"', en: '"Tonkotsu ramen, firm noodles, extra egg, no spring onion — right?"' },
    recapFocus: true,
    menu: INTL_MENU,
    modifiers: ['ajitama', 'extra_chashu', 'kaedama', 'add_bacon', 'extra_cheese', 'sauce_side', 'takeaway'],
    generic: [{ key: 'food', th: 'อาหาร', en: 'food', kw: ['อาหาร', 'something to eat', 'food'], filter: () => true }],
    opening: { th: 'สวัสดีครับ ยินดีต้อนรับครับ วันนี้มีทั้งอาหารญี่ปุ่น อิตาเลียน อเมริกัน อินเดีย และเกาหลี รับอะไรดีครับ?', en: 'Good evening and welcome! We serve Japanese, Italian, American, Indian and Korean dishes — what would you like?' },
    askItem: { th: 'รับเมนูไหนดีครับ?', en: 'Which dish would you like?' },
    recommend: { th: 'แนะนำราเมงซุปทงคตสึ กับสเต๊กริบอายครับ', en: 'I recommend the tonkotsu ramen or the ribeye steak.' },
    polite: 'ครับ',
    missions: [
      { id: 'i1', th: 'ราเมงสายเข้ม', en: 'Serious Ramen',
        brief: { th: 'สั่งราเมงซุปทงคตสึ เส้นแข็ง เพิ่มไข่ยางมะตูม ไม่ใส่ต้นหอม', en: 'Order tonkotsu ramen, firm noodles, add a ramen egg, no spring onion' },
        target: { item: 'in_01', options: { broth: 'tonkotsu', firmness: 'firm' }, modifiers: ['ajitama', 'no_spring_onion'], quantity: 1 } },
      { id: 'i2', th: 'สเต๊กมื้อพิเศษ', en: 'Steak Night',
        brief: { th: 'สั่งสเต๊กริบอาย มีเดียมแรร์ ซอสพริกไทยดำ กับสลัด และขอแยกซอส', en: 'Order a ribeye, medium rare, black pepper sauce on the side, with salad' },
        target: { item: 'in_05', options: { doneness: 'medium_rare', steak_sauce: 'black_pepper', side: 'salad' }, modifiers: ['sauce_side'], quantity: 1 } },
      { id: 'i3', th: 'เบอร์เกอร์ไม่ใส่ผักดอง', en: 'Burger, No Pickles',
        brief: { th: 'สั่งเบอร์เกอร์เนื้อ สุกมาก กับเฟรนช์ฟรายส์ ไม่ใส่แตงกวาดอง เพิ่มเบคอน', en: 'Order a beef burger, well done, with fries, no pickles, add bacon' },
        target: { item: 'in_04', options: { doneness: 'well_done', side: 'fries' }, modifiers: ['no_pickles', 'add_bacon'], quantity: 1 } },
      { id: 'i4', th: 'แพ้กลูเตน', en: 'Gluten-free Please', profile: { allergies: ['gluten'] },
        brief: { th: 'คุณแพ้กลูเตน อยากกินบัตเตอร์ชิคเก้น เผ็ดกลาง — แจ้งพนักงาน แล้วเลือกของทานคู่ที่ไม่มีแป้งสาลี', en: 'You are allergic to gluten and want butter chicken, medium spicy — tell the server and choose a gluten-free side' },
        target: { item: 'in_06', options: { spice: 'medium', carb: 'rice' }, quantity: 1 } },
      { id: 'i5', th: 'พิซซ่าปาร์ตี้', en: 'Pizza Party',
        brief: { th: 'สั่งพิซซ่ามาร์การิต้า ถาดใหญ่ ขอบชีส 2 ถาด', en: 'Order 2 large Margherita pizzas with cheese-stuffed crust' },
        target: { item: 'in_02', options: { pizza_size: 'large', crust: 'cheese_crust' }, quantity: 2 } },
    ],
  },

  juice: {
    id: 'juice', code: '2.3', icon: '🍵', th: 'น้ำผลไม้และมัทฉะ', en: 'Juice & Matcha Bar',
    staff: { th: 'พนักงานร้านน้ำ', en: 'Drinks staff', emoji: '🧑‍🍳' },
    customer: { emoji: '🧑' },
    unit: { th: 'แก้ว', en: 'glass' },
    decor: '🍊 🍉 🥭 🍵 🥬 🍋',
    focus: { th: 'ปรับแต่งเครื่องดื่มละเอียด: น้ำแข็ง ความหวาน ความเข้มมัทฉะ นมทางเลือก ท็อปปิ้ง', en: 'Fine-tune your drink: ice, sweetness, matcha strength, alt milk, toppings' },
    tip: { th: 'ครั้งหน้าลองบอก น้ำแข็ง ความหวาน และไซส์ ไปพร้อมกันเลย', en: 'Next time, give ice, sweetness and size in one go' },
    recapExample: { th: '"มัทฉะลาเต้เย็น นมโอ๊ต หวานน้อย เข้มข้นค่ะ"', en: '"Iced matcha latte, oat milk, less sweet, strong — right?"' },
    menu: JUICE_MENU,
    modifiers: ['boba', 'chia', 'coconut_jelly', 'honey', 'whipped', 'no_straw', 'takeaway'],
    generic: [
      { key: 'juice', th: 'น้ำผลไม้', en: 'juices', kw: ['น้ำผลไม้', 'น้ำปั่น', 'juice', 'smoothie'], filter: (it) => !!it.juice },
      { key: 'matcha', th: 'มัทฉะ', en: 'matcha drinks', kw: ['ชาเขียว', 'green tea'], filter: (it) => !!it.matcha },
    ],
    opening: { th: 'สวัสดีครับ รับน้ำผลไม้สดหรือมัทฉะดีครับ?', en: 'Hi there! Fresh juice or matcha today?' },
    askItem: { th: 'รับเมนูไหนดีครับ?', en: 'Which drink would you like?' },
    recommend: { th: 'มัทฉะลาเต้นมโอ๊ตขายดีที่สุด ถ้าอยากสดชื่นแนะนำมัทฉะยูซุโซดาครับ', en: 'The oat-milk matcha latte is our best seller; for something refreshing, try the matcha yuzu soda.' },
    polite: 'ครับ',
    missions: [
      { id: 'j1', th: 'มัทฉะสายเข้ม', en: 'Strong Matcha',
        brief: { th: 'สั่งมัทฉะลาเต้เย็น นมโอ๊ต หวานน้อย มัทฉะเข้มข้น', en: 'Order an iced matcha latte with oat milk, less sweet, strong matcha' },
        target: { item: 'jm_05', options: { temperature: 'iced', milk: 'oat', sweetness: 'less', matcha_level: 'strong' }, quantity: 1 } },
      { id: 'j2', th: 'น้ำส้มสายสุขภาพ', en: 'Healthy OJ',
        brief: { th: 'สั่งน้ำส้มคั้นสด ไม่ใส่น้ำแข็ง ไม่หวาน ไซส์ใหญ่', en: 'Order a large fresh orange juice, no ice, no sugar' },
        target: { item: 'jm_01', options: { ice: 'none', sweetness: 'none', size: 'large' }, quantity: 1 } },
      { id: 'j3', th: 'สมูทตี้ไม่มีนม', en: 'Dairy-free Smoothie', profile: { allergies: ['dairy'] },
        brief: { th: 'คุณแพ้นมวัว อยากได้สมูทตี้มะม่วง หวานปกติ ไซส์ปกติ — ต้องไม่มีโยเกิร์ต', en: 'You are allergic to dairy and want a regular mango smoothie, normal sweetness — no yogurt!' },
        target: { item: 'jm_03', options: { base: ['coconut', 'fruit'], sweetness: 'normal', size: 'regular' }, quantity: 1 } },
      { id: 'j4', th: 'ดีท็อกซ์ใส่เจีย', en: 'Detox + Chia',
        brief: { th: 'สั่งกรีนดีท็อกซ์ น้ำแข็งน้อย ไซส์ปกติ ไม่ใส่ขิง เพิ่มเมล็ดเจีย และไม่รับหลอด', en: 'Order a regular green detox, light ice, no ginger, add chia seeds, no straw' },
        target: { item: 'jm_04', options: { ice: 'less', size: 'regular' }, modifiers: ['no_ginger', 'chia', 'no_straw'], quantity: 1 } },
    ],
  },

  bar: {
    id: 'bar', code: '2.4', icon: '🍹', th: 'ค็อกเทลและม็อกเทล', en: 'Cocktails & Mocktails',
    staff: { th: 'บาร์เทนเดอร์', en: 'Bartender', emoji: '🤵' },
    customer: { emoji: '🧑' },
    unit: { th: 'แก้ว', en: 'glass' },
    decor: '🍸 🍹 🥂 🍋 🍒 🍸',
    focus: { th: 'สั่งเครื่องดื่มอย่างรับผิดชอบ: ยืนยันอายุ (20+) ด้วยบัตร และเลือกแบบไม่มีแอลกอฮอล์เมื่อจำเป็น', en: 'Order responsibly: show ID to confirm you are 20+, and choose alcohol-free when needed' },
    tip: { th: 'ครั้งหน้าลองบอกว่ามีแอลกอฮอล์หรือเวอร์จิ้น พร้อมรายละเอียดอื่นในประโยคเดียว', en: 'Next time, say with alcohol or virgin together with the other details' },
    recapExample: { th: '"โมจิโต้แบบมีแอลกอฮอล์ หวานน้อยนะครับ"', en: '"One mojito with alcohol, less sweet — right?"' },
    recapFocus: true,
    ageCheck: true, legalAge: 20,
    menu: BAR_MENU,
    modifiers: ['double_shot', 'no_straw'],
    generic: [
      { key: 'cocktail', th: 'ค็อกเทล', en: 'cocktails', kw: ['ค็อกเทล', 'cocktail', 'something strong'], filter: (it) => !!(it.alcoholic || it.groups.includes('alcohol')) },
      { key: 'mocktail', th: 'ม็อกเทล', en: 'mocktails', kw: ['ม็อกเทล', 'ไม่มีแอลกอฮอล์', 'mocktail', 'soft drink', 'non-alcoholic drink'], filter: (it) => !it.alcoholic },
    ],
    opening: { th: 'สวัสดีครับ ยินดีต้อนรับสู่บาร์ครับ รับค็อกเทลหรือม็อกเทลดีครับ?', en: 'Evening! Welcome to the bar — cocktail or mocktail tonight?' },
    askItem: { th: 'รับเครื่องดื่มตัวไหนดีครับ?', en: 'What can I get you?' },
    recommend: { th: 'แนะนำโมจิโต้ สดชื่นดีครับ ทำแบบเวอร์จิ้นได้ด้วย หรือจะลองอัญชันมะนาวโซดาก็ได้ครับ', en: 'The mojito is very refreshing and we can make it virgin; or try our butterfly pea lemonade.' },
    polite: 'ครับ',
    missions: [
      { id: 'k1', th: 'โมจิโต้หลังเลิกงาน', en: 'After-work Mojito', profile: { age: 25 },
        brief: { th: 'คุณอายุ 25 ปี สั่งโมจิโต้แบบมีแอลกอฮอล์ หวานน้อย — เตรียมแสดงบัตรยืนยันอายุ', en: 'You are 25. Order a mojito with alcohol, less sweet — be ready to show your ID' },
        target: { item: 'bar_01', options: { alcohol: 'with', sweetness: 'less' }, quantity: 1, idVerified: true } },
      { id: 'k2', th: 'อายุยังไม่ถึง', en: 'Not Old Enough', profile: { age: 18 },
        brief: { th: 'คุณอายุ 18 ปี เพื่อนชวนสั่งมาร์การิต้า — บอกอายุตามจริง และสั่งแบบไม่มีแอลกอฮอล์ ปั่น ขอบเกลือ', en: 'You are 18 and your friends want margaritas — be honest about your age and order a virgin frozen margarita with a salt rim' },
        target: { item: 'bar_02', options: { alcohol: 'virgin', serve: 'frozen', rim: 'salt' }, quantity: 1, alcoholFree: true } },
      { id: 'k3', th: 'ต้องขับรถกลับบ้าน', en: 'Designated Driver', profile: { age: 30, driving: true },
        brief: { th: 'คุณอายุ 30 แต่ต้องขับรถกลับบ้าน — สั่งเครื่องดื่มที่ไม่มีแอลกอฮอล์อะไรก็ได้ และขอไม่รับหลอด', en: "You are 30 but you're driving home — order any alcohol-free drink and ask for no straw" },
        target: { modifiers: ['no_straw'], quantity: 1, alcoholFree: true } },
      { id: 'k4', th: 'จินโทนิคแตงกวา', en: 'Cucumber G&T', profile: { age: 32 },
        brief: { th: 'คุณอายุ 32 สั่งจินโทนิค ตกแต่งด้วยแตงกวา แบบดับเบิ้ลช็อต', en: 'You are 32. Order a gin & tonic with cucumber garnish, make it a double' },
        target: { item: 'bar_04', options: { garnish: 'cucumber' }, modifiers: ['double_shot'], quantity: 1, idVerified: true } },
      { id: 'k5', th: 'ม็อกเทลสีม่วง', en: 'Purple Mocktail',
        brief: { th: 'สั่งอัญชันมะนาวโซดา หวานน้อย น้ำแข็งน้อย 2 แก้ว', en: 'Order 2 butterfly pea lemonades, less sweet, light ice' },
        target: { item: 'bar_05', options: { sweetness: 'less', ice: 'less' }, quantity: 2, alcoholFree: true } },
    ],
  },
};

export const SCENARIO_LIST = Object.values(SCENARIOS);
export const getScenario = (id) => SCENARIOS[id] || SCENARIO_LIST[0];
